### ISSUE TITLE
Feature Request - Teaching Material

### ISSUE THREAD

**Issue by JamesTKhan** [drdanick/raycaster-sdl#1]
Hello @drdanick ,

I have been tinkering with and learning this raycaster as I find the code very clean, well organized. I also find it unique compared to other examples I have seen so I have run into some difficulty understanding parts of it. I find raycasters interesting and would like to learn more about them. I have made minor adjustments for fun like adding mouse look and custom textures. Adding ceiling and floor textures is something I am curious to try out. 

The README indicates teaching material existed but you did not have permission to upload it. Has this situation changed or are you able to provide any further documentation on the raycaster? 

Thanks!

**Comment by drdanick** [comment]
Hi @jpooleycodes !

Thank you for the kind words! It's awesome to hear that you've been tinkering with it, and I'd love to see some of the additions you've made! (push them up to your fork 😛)

Regarding the teaching material, I've combed through what I have, and after removing some irrelevant material which I didn't own the copyright to, I believe I have a version that should be safe to upload [here](http://blueberry.drdanick.com/files/raycaster_teaching_material.zip).

The archive includes the lecture and tutorial slides I authored to teach how this engine worked to students. It's a little heavy on vector math, but hopefully that's not too big of an issue. I recommend the lecture slides for the most part, as they go into a little more detail than the tutorial slides.

Let me know if you have any more questions about the engine, I'd be happy to help out 🙂

**Comment by JamesTKhan** [comment]
Thank you! I am still processing them but the lecture slides are extremely helpful. It is clear a lot of time went into this. I started brushing up on vector math after discovering this repo. I will see what I can apply from these guides and if my code is not terrible I will get some updates pushed to my fork.
